### ISSUE TITLE
Registration and vouchers

### ISSUE THREAD

**Issue by bmann** [ChainAgnostic/Gatherings#10]
This is the "request to attend" page? https://office.ethberl.in/form/#/2/form/view/MhlX1xhzPW6dLVJ+D3u5vSdmdp2DwTSyfhcusaC2isk/

Can we make it so no voucher is needed here? https://ticketh.xyz/casa/berlin/ -- @ligi I don't totally understand why vouchers are needed.

Also: I made a simple Luma for this as well, which we might use as the main web page / email communications? https://lu.ma/m455ikms -- I'm the "host" right now, Ligi I can invite you / others there too.

@ligi I think we're going to need to make this a bit clearer if we want more people to come.

**Comment by ligi** [comment]
OK - I removed the need for a voucher. Thought initially after the Amsterdam one we are size constraint as c-base venue is smaller than the Amsterdam one - but seems we can still lower the barrier to not need a voucher
