### ISSUE TITLE
After party and other important CASA Berlin details

### ISSUE THREAD

**Issue by bmann** [ChainAgnostic/Gatherings#3]
Hi @ligi thanks so much for organizing CBase and getting tickets flowing. 

I have a bunch of questions that I'm just going to list here for asynch discussion. I'm willing to help with these items and have folks from my team that can help too.

Can we use the CBase space at end of day for after party / social or should we go somewhere else?

Should we have a kick off live call with organizers?

Is there an organizer and/or attendee chat channel for this setup?

Is this issue queue Ok to use for Gatherings tasks ;) ?

**Comment by ligi** [comment]
> Can we use the CBase space at end of day for after party / social or should we go somewhere else?

we can stay there as long as we want - should just not be a loud party - but sitting/drinking/talking is no problem

> Should we have a kick off live call with organizers?

we had it in our last monthly for a short time - but yea - maybe a separate call can be nice

> Is there an organizer and/or attendee chat channel for this setup?

there is a discord (pragmatic choice) and now a room for this gathering. Hope we can move to something like [matrix] for it 

> Is this issue queue Ok to use for Gatherings tasks ;) ?

sure thing!

**Comment by bmann** [comment]
I'll close this and file additional issues here to track work to be done.
