### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by orenyomtov** [ChainAgnostic/Gatherings#5]
The contract form link here:
https://github.com/ChainAgnostic/Gatherings/blob/main/2022-09-15-BLN-blockchainweek.berlin/README.md

Which points to:
https://office.ethberl.in/form/#/3/form/view/d3bec3ca7afbdcf4dca0840f168b27b4

Says
> This link was copied from the browser's address bar and does not provide access to the document. Please use the  Share menu to share directly with contacts or copy the link. 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/168856/183293016-f7b47269-f5a8-40d1-b02f-95f1a1a9d870.png">

Also, a drive-by question: is registration required to attend the event, or is this event open for all to participate and there is no registration?

**Comment by ligi** [comment]
thanks! Fixed in #6 
Registration is needed unfortunately so we can manage the venue capacity

**Comment by orenyomtov** [comment]
@ligi where can I register?

**Comment by ligi** [comment]
with the fixed link ;-)

**Comment by orenyomtov** [comment]
Oh my bad, I thought it's only for those who want to propose a talk - registered :)
