### ISSUE TITLE
Whiteboard rental

### ISSUE THREAD

**Issue by bmann** [ChainAgnostic/Gatherings#8]
Investigate white board rental in Berlin for Sept 15th, 2022.

3x large whiteboards, drop off in the morning, pickup the evening or next day

**Comment by ligi** [comment]
Maybe we can share with ETHMagicians happening the Sunday before our event - I guess the pick-up/drop-off will be the most expensive part here.  Also let's check how expensive buying them is - maybe we can make a deal with the EF office that IMHO could use them afterwards - maybe they could chip in here also.
Renting them seems very expensive doing a first research - but there are some used ones for very cheap on kleinanzeigen: https://www.ebay-kleinanzeigen.de/s-anzeige/whiteboard/2192135025-93-3352
I could pick them up with my cargoshuttle

**Comment by anettrolikova** [comment]
EF office has big whiteboard, which we borrowed (and transferred via uban - subway) to Metacartel demo day where we had  FEM Council. I'm pretty sure Maurice is happy to borrow it for CASA gathering too. We will leave you whiteboard markers which we would like to donate to cbase or anyone else after the event.

If you need more then probably consider buying them and eventually donating to cbase if they are open to take them or EF office. Also Parity has office in Berlin and I'm pretty sure they have some spare whiteboards. Not sure about the connection/relationship between Parity and CASA but I'm sure there is a way how to communicate.

**Comment by ligi** [comment]
@anettrolikova the main problem with borrowing the EF whiteboard is that the office is really used/crowded at the time and so it might be more problematic borrowing it at this time than it was last time. But I will ask @mvglasenapp next time I see him
