### ISSUE TITLE
CASA C-Base Merge Social

### ISSUE THREAD

**Issue by bmann** [ChainAgnostic/Gatherings#9]
@bmann set up a Luma page https://lu.ma for this, start with 100 capacity. Also ask CASA folks to register if they stay for the evening.

**Comment by bmann** [comment]
@ligi cash bar available?

Fission can sponsor some drinks and food ordering in, we don't need to go overboard. I bet other CASA folks would also chip in.

Maybe we can have some screens available showing Merge approaching.

**Comment by ligi** [comment]
Yes - there is a bar that accepts cash - we can also pre-purchase vouchers 100Drinks for 200€
There are some extra screens - we would just need some devices for the content - e.g. some PIs or whatnot.

**Comment by bmann** [comment]
I put a Luma up https://lu.ma/3uu6s45t -- set capacity to 100 for now, and linked it in the agenda
